<?php // this is an autogenerated file - do not edit (created Thu, 13 Oct 2011 15:48:37 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'address' => '/Effectivity.php',
            'addresseffectivity' => '/Effectivity.php',
            'auditlogger' => '/AuditLog.php',
            'auditlogmessage' => '/AuditLog.php',
            'customer' => '/AuditLog.php',
            'daterange' => '/Effectivity.php',
            'person' => '/Effectivity.php',
            'personsnapshot' => '/Snapshot.php',
            'personversion' => '/TemporalObject.php',
            'snapshotperson' => '/Snapshot.php',
            'spriebsch\\datetime\\datetime' => '/DateTime.php',
            'spriebsch\\temporalpatterns\\auditlog\\auditlogger' => '/AuditLog/AuditLogger.php',
            'spriebsch\\temporalpatterns\\auditlog\\auditloggeraware' => '/AuditLog/AuditLoggerAware.php',
            'spriebsch\\temporalpatterns\\auditlog\\auditloggerinterface' => '/AuditLog/AuditLoggerInterface.php',
            'spriebsch\\temporalpatterns\\auditlog\\auditlogmessage' => '/AuditLog/AuditLogMessage.php',
            'spriebsch\\temporalpatterns\\auditlog\\person' => '/AuditLog/Person.php',
            'temporalcollection' => '/TemporalCollection.php',
            'temporalobjectperson' => '/TemporalObject.php',
            'temporalpropertyperson' => '/TemporalProperty.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
