<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart 
// this is an autogenerated file - do not edit
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'spriebsch\\temporalpatterns\\auditlog\\auditlogger' => '/AuditLog/AuditLogger.php',
            'spriebsch\\temporalpatterns\\auditlog\\auditloggeraware' => '/AuditLog/AuditLoggerAware.php',
            'spriebsch\\temporalpatterns\\auditlog\\auditloggerinterface' => '/AuditLog/AuditLoggerInterface.php',
            'spriebsch\\temporalpatterns\\auditlog\\auditlogmessage' => '/AuditLog/AuditLogMessage.php',
            'spriebsch\\temporalpatterns\\auditlog\\domainobject' => '/AuditLog/DomainObject.php',
            'spriebsch\\temporalpatterns\\auditlog\\person' => '/AuditLog/Person.php',
            'spriebsch\\temporalpatterns\\effectivity\\address' => '/Effectivity/Address.php',
            'spriebsch\\temporalpatterns\\effectivity\\addresseffectivity' => '/Effectivity/AddressEffectivity.php',
            'spriebsch\\temporalpatterns\\effectivity\\daterange' => '/Effectivity/DateRange.php',
            'spriebsch\\temporalpatterns\\effectivity\\person' => '/Effectivity/Person.php',
            'spriebsch\\temporalpatterns\\snapshot\\person' => '/Snapshot/Person.php',
            'spriebsch\\temporalpatterns\\snapshot\\personsnapshot' => '/Snapshot/PersonSnapshot.php',
            'spriebsch\\temporalpatterns\\temporalcollection' => '/TemporalCollection.php',
            'spriebsch\\temporalpatterns\\temporalobject\\person' => '/TemporalObject/Person.php',
            'spriebsch\\temporalpatterns\\temporalobject\\personversion' => '/TemporalObject/PersonVersion.php',
            'spriebsch\\temporalpatterns\\temporalproperty\\person' => '/TemporalProperty/Person.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
// @codeCoverageIgnoreEnd
